version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: etl_postgres
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
